const CONFIG={leagueId:'1315912688991227904',worker:'https://the-combine.rkunka31.workers.dev',api:'https://api.sleeper.app/v1'};
const state={league:null,nfl:null,users:[],rosters:[],transactions:[],picks:[],drafts:[],userMap:new Map(),rosterMap:new Map()};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const num=(v,d=0)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const initials=s=>(s||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const teamName=r=>{const u=state.userMap.get(r.owner_id);return u?.metadata?.team_name||u?.display_name||`Team ${r.roster_id}`};
const ownerName=r=>state.userMap.get(r.owner_id)?.display_name||'Vacant';
const record=r=>{const s=r.settings||{};return `${s.wins||0}-${s.losses||0}${s.ties?`-${s.ties}`:''}`};
const pf=r=>(r.settings?.fpts||0)+(r.settings?.fpts_decimal||0)/100;
const pa=r=>(r.settings?.fpts_against||0)+(r.settings?.fpts_against_decimal||0)/100;
const maxpf=r=>(r.settings?.ppts||0)+(r.settings?.ppts_decimal||0)/100;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
async function get(path){const r=await fetch(`${CONFIG.api}${path}`);if(!r.ok)throw new Error(`${r.status} ${path}`);return r.json()}
function setStatus(type,label){const el=$('#live-status');el.className=`live-status ${type}`;el.querySelector('span').textContent=label}
function sortRosters(){return [...state.rosters].sort((a,b)=>{const A=a.settings||{},B=b.settings||{};return (B.wins||0)-(A.wins||0)||pf(b)-pf(a)})}
function table(rows,limit){const data=limit?rows.slice(0,limit):rows;return `<div class="table-wrap"><table class="league-table"><thead><tr><th>Team</th><th>Record</th><th>PF</th><th>PA</th><th>Max PF</th></tr></thead><tbody>${data.map((r,i)=>`<tr><td><div class="team-cell"><span class="rank">${i+1}</span><span class="avatar">${initials(teamName(r))}</span><span><strong>${esc(teamName(r))}</strong><small>${esc(ownerName(r))}</small></span></div></td><td>${record(r)}</td><td>${num(pf(r),1)}</td><td>${num(pa(r),1)}</td><td>${num(maxpf(r),1)}</td></tr>`).join('')}</tbody></table></div>`}
function transactionText(t){const adds=Object.keys(t.adds||{}).length,drops=Object.keys(t.drops||{}).length;if(t.type==='trade')return `Trade completed between ${[...new Set([...(Object.values(t.adds||{})),...(Object.values(t.drops||{}))])].map(id=>state.rosterMap.get(id)).filter(Boolean).map(teamName).slice(0,3).join(' and ')||'league teams'}.`;if(t.type==='waiver')return `Waiver claim processed with ${adds} addition${adds===1?'':'s'} and ${drops} drop${drops===1?'':'s'}.`;return `Roster move: ${adds} added, ${drops} dropped.`}
function renderTransactions(target,limit=20){const el=$(target);if(!state.transactions.length){el.innerHTML='<div class="loading-block">No recent transactions were returned by Sleeper.</div>';return}el.innerHTML=state.transactions.slice(0,limit).map(t=>`<div class="feed-item"><div class="feed-icon">${t.type==='trade'?'⇄':t.type==='waiver'?'$':'+'}</div><div><strong>${t.type==='trade'?'Trade':t.type==='waiver'?'Waiver claim':'Roster move'}</strong><p>${esc(transactionText(t))}</p></div></div>`).join('')}
function renderLeaders(){const rows=sortRosters();if(!rows.length)return;const pfLead=[...rows].sort((a,b)=>pf(b)-pf(a))[0],maxLead=[...rows].sort((a,b)=>maxpf(b)-maxpf(a))[0],recordLead=rows[0];$('#leader-cards').innerHTML=[["Best record",recordLead,record(recordLead)],["Points leader",pfLead,num(pf(pfLead),1)],["Max PF leader",maxLead,num(maxpf(maxLead),1)]].map(([label,r,val])=>`<div class="leader-card"><span>${label}</span><strong>${esc(teamName(r))}</strong><small>${val}</small></div>`).join('')}
function renderTeams(){const rows=sortRosters();$('#team-grid').innerHTML=rows.map((r,i)=>`<article class="panel team-card"><div class="team-card-top"><span class="avatar">${initials(teamName(r))}</span><div><p>#${i+1} IN THE TABLE</p><h3>${esc(teamName(r))}</h3><p>${esc(ownerName(r))}</p></div></div><div class="team-stats"><div><span>Record</span><strong>${record(r)}</strong></div><div><span>PF</span><strong>${num(pf(r),1)}</strong></div><div><span>Max PF</span><strong>${num(maxpf(r),1)}</strong></div></div></article>`).join('')}
function renderDraft(){const years=[2027,2028,2029],rounds=[1,2,3],rows=sortRosters(),ownership=new Map();state.picks.forEach(p=>ownership.set(`${p.season}-${p.round}-${p.roster_id}`,p.owner_id));$('#draft-board').innerHTML=years.map(year=>{const body=rows.map(team=>{const cells=rounds.map(round=>{const ownerId=ownership.get(`${year}-${round}-${team.roster_id}`)||team.roster_id;const owner=state.rosterMap.get(ownerId);return `<div><span class="pick-chip">${esc(owner?teamName(owner):'Unknown')}</span></div>`}).join('');return `<div><strong>${esc(teamName(team))}</strong></div>${cells}`}).join('');return `<div class="draft-grid"><div class="draft-head">${year}</div>${rounds.map(r=>`<div class="draft-head">Round ${r}</div>`).join('')}${body}</div>`}).join('')}
function renderRules(){const l=state.league,s=l.settings||{},r=l.roster_positions||[];const cards=[['League',l.name||'The Combine','Sleeper dynasty league'],['Teams',l.total_rosters||state.rosters.length,'Franchises'],['Scoring',l.scoring_settings?.rec===1.5?'Full PPR + 0.5 TEP':'Custom scoring','Reception-based scoring'],['Starting lineup',r.filter(x=>!['BN','IR','TAXI'].includes(x)).length,'Weekly starters'],['Trade deadline',s.trade_deadline?`Week ${s.trade_deadline}`:'See charter','Auto-approve trades'],['Waivers',s.waiver_type===2?'FAAB':'League settings',`${s.waiver_budget||100} budget`],['Playoffs',s.playoff_teams||6,'Teams qualify'],['Taxi squad',s.taxi_slots||5,'Development spots'],['Future picks','3 rounds','Rookie draft assets']];$('#rules-grid').innerHTML=cards.map(c=>`<article class="panel rule-card"><span>${esc(c[0])}</span><strong>${esc(c[1])}</strong><p>${esc(c[2])}</p></article>`).join('')}
function localReport(){const rows=sortRosters();if(!rows.length)return '<p>No league data available.</p>';const leader=rows[0],points=[...rows].sort((a,b)=>pf(b)-pf(a))[0],max=[...rows].sort((a,b)=>maxpf(b)-maxpf(a))[0],moves=state.transactions.filter(t=>t.type==='trade').length;return `<h2>State of the league</h2><p>${esc(teamName(leader))} currently sits first at ${record(leader)}. ${esc(teamName(points))} leads scoring with ${num(pf(points),1)} points, while ${esc(teamName(max))} owns the strongest Max PF mark at ${num(maxpf(max),1)}.</p><h2>What the numbers say</h2><p>The gap between actual points and Max PF shows where lineup decisions have mattered. Teams near the top of both categories have the clearest contender profile. Teams with stronger Max PF than record still have room to climb.</p><h2>League activity</h2><p>Sleeper returned ${state.transactions.length} recent roster transactions, including ${moves} trade${moves===1?'':'s'}. The activity feed updates from the live league each time this page loads.</p><h2>Commissioner's read</h2><p>The Combine now has one central view for the table, franchise profiles, league moves and future draft assets. Weekly editorial commentary will become stronger as the season produces more scores and transaction history.</p>`}
async function buildReport(useAI=false){const el=$('#report-copy');el.innerHTML=localReport();const rows=sortRosters();if(rows.length)$('#briefing-copy').textContent=`${teamName(rows[0])} leads the table. ${state.transactions.length} recent league moves are available in the live feed. Open the report for the full read.`;if(!useAI)return;try{el.innerHTML='<div class="loading-block">Writing a new league report...</div>';const data=rows.map(r=>({team:teamName(r),record:record(r),pf:pf(r),maxpf:maxpf(r)}));const resp=await fetch(`${CONFIG.worker}/ai`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-opus-4-5',max_tokens:900,system:'You are the sharp, funny beat writer for a competitive dynasty fantasy football league. Write concise HTML using h2 and p tags only. Be critical but not cruel. Do not invent player names or events.',messages:[{role:'user',content:`Write The Combine league report from this live data. Standings: ${JSON.stringify(data)}. Recent transaction types: ${JSON.stringify(state.transactions.map(t=>t.type))}.`}]})});if(!resp.ok)throw new Error('AI unavailable');const d=await resp.json();el.innerHTML=d.content?.[0]?.text||localReport()}catch(e){el.innerHTML=localReport();toast('Live AI report was unavailable. Showing the data report instead.')}}
function renderAll(){const rows=sortRosters();$('#dashboard-standings').innerHTML=table(rows,6);$('#standings-table').innerHTML=table(rows);renderTransactions('#dashboard-activity',5);renderTransactions('#activity-feed',40);renderLeaders();renderTeams();renderDraft();renderRules();buildReport(false);$('#team-count').textContent=state.rosters.length;$('#season-label').textContent=state.league.season||'2026';$('#week-label').textContent=state.nfl?.season_type==='pre'?`Preseason, Week ${state.nfl.week||1}`:`${state.nfl?.season_type||'Season'}, Week ${state.nfl?.week||1}`;$('#report-date').textContent=new Date().toLocaleDateString('en-CA',{year:'numeric',month:'long',day:'numeric'});setStatus('live','Live Sleeper data')}
async function load(){try{setStatus('','Connecting');const [league,nfl,users,rosters,picks,drafts]=await Promise.all([get(`/league/${CONFIG.leagueId}`),get('/state/nfl'),get(`/league/${CONFIG.leagueId}/users`),get(`/league/${CONFIG.leagueId}/rosters`),get(`/league/${CONFIG.leagueId}/traded_picks`),get(`/league/${CONFIG.leagueId}/drafts`)]);Object.assign(state,{league,nfl,users,rosters,picks,drafts});users.forEach(u=>state.userMap.set(u.user_id,u));rosters.forEach(r=>state.rosterMap.set(r.roster_id,r));const weeks=[nfl.week||1,Math.max(1,(nfl.week||1)-1),1];const tx=await Promise.allSettled([...new Set(weeks)].map(w=>get(`/league/${CONFIG.leagueId}/transactions/${w}`)));state.transactions=tx.flatMap(x=>x.status==='fulfilled'?x.value:[]).sort((a,b)=>(b.status_updated||b.created||0)-(a.status_updated||a.created||0));renderAll()}catch(e){console.error(e);setStatus('error','Connection error');$$('.loading-block').forEach(el=>el.innerHTML='<div class="error-state">Sleeper data did not load. Refresh the page to try again.</div>')}}
function showView(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#mobile-menu').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${view}`)}
$$('.nav-link').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jump)));$('#menu-button').addEventListener('click',()=>$('#mobile-menu').classList.toggle('open'));$('#refresh-report').addEventListener('click',()=>buildReport(true));$('#sleeper-link').href=`https://sleeper.com/leagues/${CONFIG.leagueId}`;const initial=location.hash.slice(1);if(initial&&$(`#view-${initial}`))showView(initial);load();