const CFG={leagueId:'1315912688991227904',api:'https://api.sleeper.app/v1',worker:'https://the-combine.rkunka31.workers.dev'};
const S={league:{},state:{},users:[],rosters:[],players:{},drafts:[],draftPicks:[],tradedPicks:[],matchups:[],userMap:new Map(),rosterMap:new Map()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number(v||0).toFixed(1);
const initials=s=>(s||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const get=async path=>{const r=await fetch(CFG.api+path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${path}`);return r.json()};
const teamName=r=>{const u=S.userMap.get(r?.owner_id);return u?.metadata?.team_name||u?.display_name||`Team ${r?.roster_id||''}`};
const ownerName=r=>S.userMap.get(r?.owner_id)?.display_name||'Vacant';
const pf=r=>(r?.settings?.fpts||0)+(r?.settings?.fpts_decimal||0)/100;
const maxpf=r=>(r?.settings?.ppts||0)+(r?.settings?.ppts_decimal||0)/100;
const record=r=>`${r?.settings?.wins||0}-${r?.settings?.losses||0}`;
const sortedRosters=()=>[...S.rosters].sort((a,b)=>(b.settings?.wins||0)-(a.settings?.wins||0)||pf(b)-pf(a));
const playerName=id=>S.players[id]?.full_name||id;

const NAV=[['dashboard','Dashboard'],['standings','Standings'],['draft','Draft'],['analytics','Analytics'],['autopsy','Team Analysis'],['payments','Payments'],['contacts','Contacts'],['report','League Report'],['charter','Charter']];
function setStatus(type,text){const el=$('#live-status');if(!el)return;el.className=`live-status ${type||''}`.trim();const span=el.querySelector('span');if(span)span.textContent=text}
function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#mobile-menu')?.classList.remove('open');history.replaceState(null,'',`#${view}`);scrollTo(0,0)}
window.show=show;
function mountExtraViews(){const main=document.querySelector('main');if(!main)return;if(!$('#view-autopsy'))main.insertAdjacentHTML('beforeend',`<section class="view" id="view-autopsy"><div class="page-head shell"><p class="eyebrow">FRANCHISE EVALUATION</p><h1>Team analysis</h1><p>Roster strength, age profile, positional balance and future assets.</p></div><div class="shell"><div id="autopsy-output" class="loading-block">Loading team analysis...</div></div></section>`);if(!$('#view-payments'))main.insertAdjacentHTML('beforeend',`<section class="view" id="view-payments"><div class="page-head shell"><p class="eyebrow">LEAGUE TREASURY</p><h1>Payment tracker</h1><p>All owners are paid for 2026 and 2027.</p></div><div class="shell"><div id="payment-output" class="panel loading-block">Loading payment status...</div></div></section>`)}
function setupNav(){mountExtraViews();const html=NAV.map(([id,label],i)=>`<button class="nav-link${i?'':' active'}" data-view="${id}">${label}</button>`).join('');$('#desktop-nav').innerHTML=html;$('#mobile-menu').innerHTML=html;$$('.nav-link').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));$('#menu-button').onclick=()=>$('#mobile-menu').classList.toggle('open');$('#sleeper-link').href=`https://sleeper.com/leagues/${CFG.leagueId}`}
function table(rows,limit){const data=limit?rows.slice(0,limit):rows;return `<div class="table-wrap"><table class="league-table"><thead><tr><th>Team</th><th>Record</th><th>PF</th><th>Max PF</th></tr></thead><tbody>${data.map((r,i)=>`<tr><td><div class="team-link"><span class="rank">${i+1}</span><span class="avatar">${initials(teamName(r))}</span><span><strong>${esc(teamName(r))}</strong><small>${esc(ownerName(r))}</small></span></div></td><td>${record(r)}</td><td>${fmt(pf(r))}</td><td>${fmt(maxpf(r))}</td></tr>`).join('')}</tbody></table></div>`}
function renderStandings(){const rows=sortedRosters();const dash=$('#dashboard-standings'),full=$('#standings-table');if(dash)dash.innerHTML=table(rows,6);if(full)full.innerHTML=table(rows);const leaders=$('#leader-cards');if(leaders&&rows.length){const points=[...rows].sort((a,b)=>pf(b)-pf(a))[0],max=[...rows].sort((a,b)=>maxpf(b)-maxpf(a))[0];leaders.innerHTML=[["Best record",rows[0],record(rows[0])],["Points leader",points,fmt(pf(points))],["Max PF leader",max,fmt(maxpf(max))]].map(([label,r,val])=>`<div class="leader-card"><span>${label}</span><strong>${esc(teamName(r))}</strong><small>${val}</small></div>`).join('')}}
function renderPayments(){const el=$('#payment-output');if(!el)return;el.innerHTML=sortedRosters().map(r=>`<div class="payment-row" style="display:grid;grid-template-columns:44px 1fr auto auto;gap:12px;align-items:center;padding:15px;border-bottom:1px solid var(--line)"><span class="avatar">${initials(teamName(r))}</span><div><strong>${esc(teamName(r))}</strong><small>${esc(ownerName(r))}</small></div><span class="pick-chip">2026 PAID</span><span class="pick-chip">2027 PAID</span></div>`).join('')}
function renderContacts(){const el=$('#contact-grid');if(!el)return;el.innerHTML=sortedRosters().map(r=>{const u=S.userMap.get(r.owner_id);return `<article class="panel contact-card"><span class="avatar">${initials(teamName(r))}</span><div><h3>${esc(teamName(r))}</h3><p>${esc(ownerName(r))}</p><small>@${esc(u?.display_name||'')}</small></div><div class="contact-actions"><span>Private contact details require server-side authentication.</span></div></article>`}).join('')}
function renderTeamAnalysis(){const el=$('#autopsy-output');if(!el)return;const rows=sortedRosters().map(r=>{const ps=(r.players||[]).map(id=>S.players[id]).filter(Boolean),ages=ps.map(p=>Number(p.age)).filter(Boolean),age=ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:27;const counts=Object.fromEntries(['QB','RB','WR','TE'].map(pos=>[pos,ps.filter(p=>p.position===pos).length]));const dynasty=Math.max(45,Math.min(95,Math.round(94-(age-24)*4.5)));const redraft=Math.max(45,Math.min(95,Math.round(55+Math.min(40,maxpf(r)/40))));const balance=Math.max(45,100-(Math.abs(counts.QB-3)*5+Math.abs(counts.RB-6)*4+Math.abs(counts.WR-8)*3+Math.abs(counts.TE-3)*5));const depth=Math.max(45,Math.min(95,Math.round(50+ps.length*1.7)));const overall=Math.round(dynasty*.3+redraft*.3+balance*.2+depth*.2);const top=ps.slice().sort((a,b)=>(a.age||99)-(b.age||99)).slice(0,3).map(p=>p.full_name).filter(Boolean);const thin=Object.entries(counts).sort((a,b)=>a[1]-b[1])[0];return{r,overall,dynasty,redraft,balance:Math.round(balance),depth,age:age.toFixed(1),top,thin}}).sort((a,b)=>b.overall-a.overall);el.className='';el.innerHTML=`<div class="team-grid">${rows.map((x,i)=>`<article class="panel team-card"><div class="team-card-top"><span class="avatar">${initials(teamName(x.r))}</span><div><p>#${i+1} OVERALL</p><h3>${esc(teamName(x.r))}</h3><p>${esc(ownerName(x.r))}</p></div></div><div class="team-stats"><div><span>Overall</span><strong>${x.overall}</strong></div><div><span>Dynasty</span><strong>${x.dynasty}</strong></div><div><span>Redraft</span><strong>${x.redraft}</strong></div></div><p class="roster-mix">Balance ${x.balance} · Depth ${x.depth} · Avg age ${x.age}</p><p>${x.top.length?`${esc(x.top.join(', '))} carry the long-term profile. `:''}${x.thin[0]} depth is the obvious weak point. The roster grade is based on age, current production, positional balance and roster depth.</p></article>`).join('')}</div>`}
function originalRoster(d,p){const order=d?.draft_order||{};const uid=Object.keys(order).find(id=>Number(order[id])===Number(p.draft_slot));return uid?S.rosters.find(r=>r.owner_id===uid):null}
async function renderDraft(){const board=$('#draft-board'),recap=$('#draft-recap-copy');try{const d=S.drafts.find(x=>x.status==='complete')||S.drafts[0];if(!d)throw new Error('No draft found');S.draftPicks=await get(`/draft/${d.draft_id}/picks`);board.innerHTML=`<div class="panel-head"><div><p class="kicker">${esc(d.season||'')} DRAFT</p><h2>${S.draftPicks.length} selections</h2></div></div><div class="draft-board-grid">${S.draftPicks.map(p=>`<div class="draft-pick"><span>Pick ${p.pick_no}</span><strong>${esc(`${p.metadata?.first_name||''} ${p.metadata?.last_name||''}`.trim())}</strong><small>${esc(p.metadata?.position||'')} · ${esc(teamName(S.rosterMap.get(Number(p.roster_id))))}</small></div>`).join('')}</div>`;const by={};S.draftPicks.forEach(p=>(by[p.round]??=[]).push(p));recap.innerHTML=`<h2>Draft analysis</h2><p>${S.draftPicks.length} selections reviewed.</p>${Object.entries(by).map(([round,picks])=>{const traded=picks.filter(p=>{const orig=originalRoster(d,p),sel=S.rosterMap.get(Number(p.roster_id));return orig&&sel&&orig.roster_id!==sel.roster_id});const positions={};picks.forEach(p=>positions[p.metadata?.position]=(positions[p.metadata?.position]||0)+1);const run=Object.entries(positions).sort((a,b)=>b[1]-a[1])[0];return `<section class="round-roast"><h2>Round ${round}</h2><p>${run?`${run[0]} led the round with ${run[1]} selections. `:''}${traded.length?`${traded.length} draft slot${traded.length===1?' changed':'s changed'} hands.`:'No draft slots changed hands.'}</p>${picks.map(p=>{const sel=S.rosterMap.get(Number(p.roster_id)),orig=originalRoster(d,p),changed=orig&&sel&&orig.roster_id!==sel.roster_id;return `<p><strong>${p.pick_no}. ${esc(`${p.metadata?.first_name||''} ${p.metadata?.last_name||''}`.trim())}</strong> · ${esc(teamName(sel))}${changed?`<br><span class="draft-trade">Original slot: ${esc(teamName(orig))}. Pick used by ${esc(teamName(sel))}.</span>`:''}</p>`}).join('')}</section>`}).join('')}`;renderFuturePicks()}catch(e){console.error(e);if(board)board.innerHTML='<div class="error-state">Draft data did not load. Tap refresh and try again.</div>';if(recap)recap.innerHTML='<p>Draft analysis did not load.</p>'}}
function renderFuturePicks(){const el=$('#draft-capital');if(!el)return;const rows=sortedRosters(),years=[2027,2028,2029],rounds=[1,2,3],ownerMap=new Map();S.tradedPicks.forEach(p=>ownerMap.set(`${p.season}-${p.round}-${p.roster_id}`,p.owner_id));el.innerHTML=years.map(y=>`<div class="draft-grid"><div class="draft-head">${y}</div>${rounds.map(r=>`<div class="draft-head">Round ${r}</div>`).join('')}${rows.map(team=>`<div><strong>${esc(teamName(team))}</strong></div>${rounds.map(r=>{const id=ownerMap.get(`${y}-${r}-${team.roster_id}`)||team.roster_id;return `<div><span class="pick-chip">${esc(teamName(S.rosterMap.get(Number(id))))}</span></div>`}).join('')}`).join('')}</div>`).join('')}
function renderAnalytics(){const out=$('#analytics-output'),summary=$('#analytics-summary');const rows=S.matchups.flatMap(w=>w.data.map(m=>({week:w.week,roster:m.roster_id,points:Number(m.points||0)})));if(!rows.length){summary.innerHTML='';out.innerHTML='<div class="error-state">No completed 2026 scoring data is available yet. Historical and projection data will be added separately.</div>';return}const map=new Map();rows.forEach(x=>{const a=map.get(x.roster)||{roster:x.roster,points:0,weeks:0};a.points+=x.points;a.weeks++;map.set(x.roster,a)});const data=[...map.values()].sort((a,b)=>b.points-a.points);summary.innerHTML=`<div class="leader-card"><span>League points</span><strong>${fmt(data.reduce((s,x)=>s+x.points,0))}</strong></div><div class="leader-card"><span>Weeks loaded</span><strong>${S.matchups.length}</strong></div><div class="leader-card"><span>Teams</span><strong>${data.length}</strong></div>`;out.innerHTML=`<div class="table-wrap"><table class="league-table"><thead><tr><th>Team</th><th>Total</th><th>Average</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(teamName(S.rosterMap.get(x.roster)))}</td><td>${fmt(x.points)}</td><td>${fmt(x.points/x.weeks)}</td></tr>`).join('')}</tbody></table></div>`}
function renderCommissionerDesk(){const box=$('#briefing-copy'),report=$('#report-copy');const currentWeek=Math.max(1,Number(S.state.week||1));const completed=S.matchups.filter(w=>w.data.some(m=>Number(m.points)>0));if(!completed.length){const text='The league is in preseason mode. Standings are live, but weekly winners and player trends will appear once the 2026 season begins.';box.textContent=text;report.innerHTML=`<h2>State of the league</h2><p>${text}</p>`;return}const latest=completed[completed.length-1],top=[...latest.data].sort((a,b)=>(b.points||0)-(a.points||0))[0],r=S.rosterMap.get(top.roster_id);box.textContent=`${teamName(r)} led Week ${latest.week} with ${fmt(top.points)} points.`;report.innerHTML=`<h2>Week ${latest.week}</h2><p>${esc(teamName(r))} set the pace with ${fmt(top.points)} points. Full matchup and player commentary will expand as the season develops.</p>`}
function bindControls(){setupNav();$$('[data-drafttab]').forEach(b=>b.onclick=()=>{$$('[data-drafttab]').forEach(x=>x.classList.toggle('active',x===b));['board','capital','recap'].forEach(id=>$(`#draft-${id}`)?.classList.toggle('hidden',id!==b.dataset.drafttab))});$('#generate-draft-roast').onclick=renderDraft;$('#refresh-report').onclick=renderCommissionerDesk;$('#contact-search').oninput=renderContacts;$('#refresh-contacts').onclick=renderContacts;const initial=location.hash.slice(1);if(initial&&$(`#view-${initial}`))show(initial)}
async function load(){setStatus('','Connecting');try{const base=await Promise.all([get(`/league/${CFG.leagueId}`),get('/state/nfl'),get(`/league/${CFG.leagueId}/users`),get(`/league/${CFG.leagueId}/rosters`)]);[S.league,S.state,S.users,S.rosters]=base;S.users.forEach(u=>S.userMap.set(u.user_id,u));S.rosters.forEach(r=>S.rosterMap.set(r.roster_id,r));const optional=await Promise.allSettled([get('/players/nfl'),get(`/league/${CFG.leagueId}/drafts`),get(`/league/${CFG.leagueId}/traded_picks`)]);S.players=optional[0].status==='fulfilled'?optional[0].value:{};S.drafts=optional[1].status==='fulfilled'?optional[1].value:[];S.tradedPicks=optional[2].status==='fulfilled'?optional[2].value:[];const week=Math.max(1,Number(S.state.week||1));const match=await Promise.allSettled(Array.from({length:week},(_,i)=>get(`/league/${CFG.leagueId}/matchups/${i+1}`).then(data=>({week:i+1,data}))));S.matchups=match.filter(x=>x.status==='fulfilled').map(x=>x.value);renderStandings();renderPayments();renderContacts();renderTeamAnalysis();renderAnalytics();renderCommissionerDesk();await renderDraft();$('#team-count').textContent=S.rosters.length;$('#season-label').textContent=S.league.season||'2026';$('#week-label').textContent=`${S.state.season_type||'Season'}, Week ${S.state.week||1}`;$('#report-date').textContent=new Date().toLocaleDateString('en-CA',{year:'numeric',month:'long',day:'numeric'});if(typeof window.charter==='function')window.charter();setStatus('live','Live Sleeper data')}catch(e){console.error(e);setStatus('error','Data unavailable');$$('.loading-block').forEach(el=>el.innerHTML='<div class="error-state">League data did not load. Refresh to try again.</div>')}}
bindControls();load();