window.COMBINE_CHARTER={version:'1.0',effective:'2026',title:'The Combine Dynasty Football League Charter',subtitle:'Governing Rules, Bylaws & Operating Procedures',meta:[['Commissioner','Rob Kunka'],['Platform','Sleeper'],['Format','Dynasty, perpetual rosters with no re-draft'],['Scoring','Full PPR plus Tight End Premium'],['Annual Fee','CAD $55, $80, or $105 per year pending league vote'],['Payment','E-Transfer to rkunka31@gmail.com'],['Teams','14'],['Hub','the-combine.ca']],tabs:[['overview','Overview'],['money','Fees & Prizes'],['rosters','Rosters & Scoring'],['drafts','Drafts'],['transactions','Waivers & Trades'],['governance','Governance'],['competition','Season & Playoffs'],['appendices','Appendices'],['bookmarks','Bookmarks']],sections:[
{id:'section-1',number:'1',tab:'overview',title:'League Overview',intro:'This charter governs all rules, conduct, financial obligations, and operating procedures for The Combine Dynasty Football League. All members are bound by this document upon joining. The League operates on the Sleeper platform and uses full PPR scoring with a tight end premium. This is a true dynasty league. Rosters carry over from year to year, with NFL rookies available each off-season.',blocks:[
{type:'table',title:'1.1 League Structure',headers:['Category','Rule'],rows:[['Teams','14 teams'],['Platform','Sleeper'],['Format','Dynasty, perpetual rosters with no re-draft'],['Scoring','Full PPR plus Tight End Premium'],['League Type','Competitive, with long-term continuity expected'],['Commissioner','Rob Kunka'],['Hub','the-combine.ca']]},
{type:'text',title:'1.2 Mission Statement',text:'The Combine is designed for committed long-term owners. Dynasty formats reward patient roster building, sharp draft strategy, and active team management over multiple seasons. All members are expected to be engaged participants throughout the year, not only during the NFL season.'},
{type:'text',title:'1.3 Communication',text:'The primary communication channel is the Sleeper league chat. All official announcements and Commissioner decisions are also posted on The Combine hub. A secondary channel will be established by league vote. Every owner must provide and keep current their email and phone number with the Commissioner, stored in The Combine hub.'},
{type:'vote',text:'Secondary communication channel: Sleeper chat, WhatsApp, email chain, or another option.'}]},
{id:'section-2',number:'2',tab:'money',title:'League Fees & Payments',intro:'All fees are in Canadian dollars. The base entry fee is subject to a league vote before the startup draft. Every option includes a CAD $5 annual operational fee.',blocks:[
{type:'vote',text:'Annual entry fee: $50 + $5 = $55, $75 + $5 = $80, or $100 + $5 = $105 per team per year.'},
{type:'table',title:'2.1 Fee Structure',headers:['Option','Base Fee','Operational','Total Per Year','Two-Year Upfront'],rows:[['A, Standard','CAD $50','CAD $5','CAD $55','CAD $110'],['B, Mid-tier','CAD $75','CAD $5','CAD $80','CAD $160'],['C, Premium','CAD $100','CAD $5','CAD $105','CAD $210']]},
{type:'note',text:'The $5 operational fee covers platform costs, The Combine hub, or player replacement. Any unused balance rolls over or is returned following a league vote. The prize pool is calculated from the base fee only.'},
{type:'list',title:'2.2 Payment Policy',items:['Two years of fees are due upfront before the startup draft or any league activity.','Renewal fees are due before each new season.','Late payment freezes the team. No roster moves, trades, or draft picks are permitted until paid.','After 30 days of non-payment, the Commissioner begins the replacement process and the owner forfeits the roster.']},
{type:'text',title:'2.3 Pick Fee Obligation',text:'An owner who trades picks into future league years is financially obligated for the entry fee in each of those years, regardless of whether they remain in the league. Incoming owners assume this obligation upon joining.'},
{type:'table',title:'2.4 Prize Pool & Payouts',headers:['Prize','Option A: 50/25/15/10','Option B: 60/20/10/10','Notes'],rows:[['Champion','50%','60%','Base prize pool'],['Runner-Up','25%','20%','Base prize pool'],['Third Place','15%','10%','Base prize pool'],['Regular Season Winner','10%','10%','Best regular-season record']]},
{type:'vote',text:'Prize pool distribution: Option A, 50/25/15/10, or Option B, 60/20/10/10.'},
{type:'note',text:'The regular-season winner is the owner with the best win-loss record across all regular-season weeks. Ties are broken by total Points For.'},
{type:'list',title:'2.5 Ownership Transfers',items:['An owner wishing to transfer or sell a team must notify the Commissioner.','The incoming owner assumes all financial obligations, including unpaid dues and pick-fee obligations.','Commissioner approval is required before a transfer is recognized.','No mid-season transfers are allowed except in extraordinary circumstances at Commissioner discretion.']}]},
{id:'section-3',number:'3',tab:'rosters',title:'Roster Construction',blocks:[
{type:'table',title:'3.1 Active Lineup, Weekly Starters',headers:['Position','Slots','Notes'],rows:[['Quarterback','1',''],['Running Back','2',''],['Wide Receiver','3',''],['Tight End','1','TEP scoring applies'],['Flex, RB/WR/TE','2','Any combination'],['Total Starters','9','14-team league']]},
{type:'table',title:'3.2 Full Roster Composition',headers:['Category','Spots','Eligibility'],rows:[['Active Roster, starters plus bench','21','All players'],['Starters','9','See Section 3.1'],['Bench','12','All players'],['Taxi Squad','5 by default','Rookies and Year 2 players only'],['Injured Reserve','5 by default','IR, Out, or PUP-designated players']]},
{type:'vote',text:'Taxi squad size: 3, 5, or 10 spots. Default is 5.'},{type:'vote',text:'IR size: 3, 5, or 10 spots. Default is 5.'},
{type:'list',title:'3.3 Taxi Squad Rules',items:['Eligible players are rookies in Year 1 and second-year players in Year 2 only.','After a player completes a second season, the player must be promoted or released before Year 3.','Once activated, a player cannot return to the taxi squad.','Taxi players may be added through the draft or waivers. They may be traded and remain on the receiving team taxi squad when space allows.','Taxi players may not start in weekly lineups.','Taxi spots do not count against the active roster limit.']},
{type:'list',title:'3.4 Injured Reserve',items:['Only players with an official IR, Out, or PUP designation are eligible.','Sleeper blocks roster moves when an ineligible player occupies an IR slot.','When a player returns from IR, the owner must move the player to an active spot or release the player before further transactions.']}]},
{id:'section-4',number:'4',tab:'rosters',title:'Scoring System',intro:'The League uses full PPR scoring with a Tight End Premium. All scoring is handled automatically through Sleeper.',blocks:[
{type:'table',headers:['Scoring Event','Points'],rows:[['Passing touchdown','4'],['Passing yard','0.04, one point per 25 yards'],['Interception thrown','-2'],['Rushing touchdown','6'],['Rushing yard','0.1, one point per 10 yards'],['Receiving touchdown','6'],['Receiving yard','0.1, one point per 10 yards'],['Reception','1'],['Tight end reception bonus','+0.5 per reception'],['Fumble lost','-2'],['Two-point conversion','2']]},
{type:'note',text:'TEP applies to tight end receptions only. Final scoring settings are locked in Sleeper. This table serves as a reference.'},
{type:'vote',text:'Confirm full PPR plus 0.5 TEP, or select a tight end premium of +0.25, +0.5, or +1.0.'}]},
{id:'section-5',number:'5',tab:'drafts',title:'Startup Draft',intro:'The startup draft is a full snake draft conducted once at the founding of the league. All NFL players, including current-year rookies, are eligible.',blocks:[
{type:'list',items:['Snake format. The order reverses each round.','The order is determined by random lottery before the draft, with no seeding advantages.','All teams participate and all roster spots, excluding taxi, are filled.','Draft picks may be traded during the startup draft, including future rookie picks and previously drafted players.','The pick clock is 24 hours. If the clock expires, the owner is notified and receives an automatic 12-hour extension. Auto-draft activates when the extension expires.','Each owner receives a maximum of three extensions across the startup draft. After all extensions are used, the 24-hour clock applies without further extensions.','Extensions are non-transferable and do not carry over between drafts.','Owners are strongly encouraged to configure a pre-draft queue in Sleeper.']},
{type:'note',text:'The Commissioner will make reasonable efforts to accommodate owner schedules, but the clock will be enforced.'}]},
{id:'section-6',number:'6',tab:'drafts',title:'Annual Rookie Draft',intro:'Each off-season, the league holds a rookie draft. Only players entering their first NFL season are eligible. Undrafted rookies become available after the draft concludes.',blocks:[
{type:'vote',text:'Rookie draft round count: 3, 4, or 5 rounds. Default is 3.'},
{type:'list',title:'6.1 Draft Order, Non-Playoff Teams',items:['Draft order is seeded by Maximum Points For across the regular season, from lowest to highest.','The lowest MaxPF receives Pick 1.','MaxPF rewards roster performance and discourages tanking.','MaxPF ties are broken by head-to-head record, then coin flip.']},
{type:'list',title:'6.1 Draft Order, Playoff Teams',items:['Playoff teams draft after all non-playoff teams and are seeded by inverse finish.','First-round exits pick first, ordered by MaxPF among themselves.','Semifinal losers pick next.','The championship loser picks second-to-last among playoff teams.','The champion picks last overall.','The same linear order applies in every round. The rookie draft is not a snake draft.']},
{type:'list',title:'6.2 Pick Trading',items:['Future rookie picks may be traded at any time, with no restriction on years out.','All pick trades are binding upon acceptance in Sleeper.','Contingent arrangements are prohibited. Every trade is unconditional.','Owners who trade future picks carry the entry-fee obligation for those years under Section 2.3.']}]},
{id:'section-7',number:'7',tab:'transactions',title:'Waivers & Free Agency',blocks:[
{type:'table',title:'7.1 FAAB System',headers:['Rule','Setting'],rows:[['System','Free Agent Acquisition Budget'],['Budget','CAD $100 per team per period, subject to vote'],['Training Camp Reset','Full reset at the start of NFL training camp'],['Offseason Reset','Full reset at the start of the offseason'],['Bidding','Blind simultaneous bids. Highest bid wins.'],['Tie-breaker','Waiver priority. Lowest priority loses ties.'],['Minimum Bid','$0 is permitted after FAAB is exhausted'],['Pickup Limits','No weekly or seasonal limits']]},
{type:'vote',text:'FAAB budget: CAD $100 or CAD $200 per period.'},
{type:'list',title:'7.2 Waiver Processing',items:['Waivers process on a Commissioner-set schedule in Sleeper.','Dropped players return to waivers before becoming free agents.','No weekly transaction limit applies when roster space exists.']}]},
{id:'section-8',number:'8',tab:'transactions',title:'Trade Rules',blocks:[
{type:'list',title:'8.1 Trade Approval',items:['All trades auto-approve when accepted by both parties. The league does not use a veto system.','The Commissioner may void a trade only in a confirmed collusion case.','An unbalanced trade alone is not grounds for review.']},
{type:'note',text:'The Combine does not use a veto system. Collusion is the only valid ground for reversal.'},
{type:'vote',text:'Trade veto system: no veto, Commissioner veto only, or 48-hour league vote.'},
{type:'table',title:'8.2 Trade Deadline',headers:['Option','Description'],rows:[['A, No Deadline, default','Trades are permitted year-round. During playoffs, non-playoff teams may not trade with active playoff teams.'],['B, Standard Deadline','Trades are permitted from the season start through two weeks before playoffs. Offseason trading reopens after the championship.']]},
{type:'vote',text:'Trade deadline policy: Option A, no deadline, or Option B, standard deadline.'},
{type:'list',title:'8.3 Collusion Policy',items:['Collusion means trading assets without fair value to benefit a specific owner playoff position.','Reports go to the Commissioner through The Combine hub or direct message.','The Commissioner reviews trade history, chat logs, and context before ruling.','Confirmed collusion results in the trade being voided and a league vote on further sanctions.','Repeat collusion results in removal from the league without a fee refund.']}]},
{id:'section-9',number:'9',tab:'governance',title:'Lineup Management & Penalties',blocks:[
{type:'list',title:'9.1 Lineup Submission',items:['Every owner must submit a valid lineup before the first game kickoff each week.','Individual slots lock at each player game kickoff.','Starting injured, bye-week, or inactive players is the owner responsibility.']},
{type:'table',title:'9.2 Penalty Schedule',headers:['Offense','Penalty','Notes'],rows:[['First','Formal documented warning','Resets each season'],['Second','$10 FAAB fine','Deducted immediately'],['Third','$20 FAAB fine','Deducted immediately'],['Fourth','$40 FAAB fine','Commissioner escalation'],['Fifth and later','Remaining FAAB plus lowest rookie pick','Counter resets each season']]},
{type:'list',items:['FAAB shortfalls carry forward to the next FAAB reset.','Appeals must be submitted within 48 hours with documented justification, such as a platform outage.']},
{type:'note',text:'Documented Sleeper failures affecting multiple owners will not result in penalties.'},
{type:'vote',text:'Confirm the lineup penalty schedule or approve an alternative at the Season 1 vote.'}]},
{id:'section-10',number:'10',tab:'governance',title:'Conduct & Governance',blocks:[
{type:'list',title:'10.1 Expected Conduct',items:['Compete in good faith every week.','Respond to trade offers within 72 hours as a courtesy standard. This is not penalized.','Participate in the rookie draft without auto-pick unless notice is given.','Maintain a respectful tone in league communications.','Notify the Commissioner promptly when unable to continue as an owner.','An owner who misses three or more consecutive lineups without prior notice is subject to removal and forfeits the current-year entry fee.']},
{type:'list',title:'10.2 Orphaned Teams',items:['The Commissioner makes reasonable efforts to contact an unresponsive owner before declaring a team orphaned.','Orphaned teams operate in maintenance-only mode, with lineups set using highest projected players and no trades.','An orphaned team does not participate in free agency.','The Commissioner seeks a replacement within 30 days.','The original owner forfeits fees paid and has no claim to prize money.']},
{type:'text',title:'10.3 Team Dissolution & Even-Team Requirement',text:'The Combine requires an even number of teams at all times. The preferred outcome for a vacancy is a replacement owner who receives the roster, picks, and draft capital.'},
{type:'list',title:'Step 1, Find a Replacement Owner',items:['The Commissioner actively recruits a replacement.','The roster, picks, and draft capital transfer to the incoming owner.']},
{type:'list',title:'Step 2, Voluntary Forfeit',items:['When no replacement is found before the next season, the Commissioner asks whether an active owner wishes to forfeit voluntarily.','The forfeiting owner receives a full refund of the current-year entry fee and prepaid future-year fees.','No owner may be compelled to forfeit.','When multiple owners volunteer, the Commissioner selects a team in consultation with the league.']},
{type:'list',title:'Step 3, Dispersal Draft',items:['After two teams are dissolved, players from both rosters enter a dispersal pool.','All remaining teams participate in a snake draft using annual rookie draft seeding rules.','The Commissioner sets the number of rounds based on pool size.','Dispersal draft picks may be traded.','Unselected players enter free agency with a $0 FAAB floor.','Picks belonging to dissolved teams are voided. Picks traded to dissolved teams return to the latest non-dissolved team in the trade chain.','When dissolution would reduce the league below 12 teams, an emergency vote must occur within seven days.']},
{type:'list',title:'10.4 Commissioner Authority, Permitted',items:['Interpret and enforce the charter.','Issue warnings, FAAB fines, or draft-pick penalties.','Void trades in confirmed collusion cases.','Suspend or remove an owner for egregious or repeated violations.','Call a league vote on matters requiring collective input.']},
{type:'list',title:'10.4 Commissioner Authority, Prohibited',items:['Alter rosters for competitive reasons.','Override trade decisions that do not involve collusion.','Change scoring settings mid-season.','Unilaterally amend the charter.']},
{type:'text',title:'10.5 Appeals',text:'Any owner may appeal a Commissioner decision through The Combine hub or Sleeper chat. A majority vote of all owners overturns the decision. The Commissioner does not vote on appeals of their own decisions.'},
{type:'list',title:'10.6 League Votes',items:['A simple majority, more than 50%, is required for most decisions.','A two-thirds majority is required for charter amendments or owner removal.','The Commissioner may vote but recuses on matters involving their own conduct.','Votes occur through The Combine hub or Sleeper poll with a 72-hour window.']},
{type:'list',title:'10.7 Commissioner Succession',items:['When the Commissioner steps down, the league elects a replacement.','Thirty days notice is preferred. The most senior member serves as interim Commissioner after a sudden departure.']}]},
{id:'section-11',number:'11',tab:'competition',title:'Regular Season & Playoffs',blocks:[
{type:'list',title:'11.1 Regular Season',items:['The regular season follows the NFL schedule, typically Weeks 1 through 14.','Sleeper generates the head-to-head schedule.','Standings use win-loss record, with MaxPF as the first tiebreaker.']},
{type:'list',title:'11.2 Playoff Structure',items:['Playoffs typically run during Weeks 15 through 17.','Seeding uses regular-season record, with MaxPF as the tiebreaker.']},
{type:'vote',text:'Playoff field size: 4, 6, or 8 qualifying teams.'},
{type:'list',title:'11.3 Regular Season Winner',items:['The best regular-season record receives 10% of the prize pool.','This prize is independent of playoff placement.','Ties are broken by total regular-season Points For.']},
{type:'list',title:'11.4 Consolation Bracket',items:['Non-playoff teams compete in a consolation bracket.','Consolation results do not affect draft order. MaxPF governs seeding.']}]},
{id:'section-12',number:'12',tab:'competition',title:'Scenarios & Edge Cases',blocks:[
{type:'list',title:'12.1 Player Eligibility',items:['Position eligibility changes apply immediately during the season.','No retroactive lineup adjustments are made.']},
{type:'list',title:'12.2 Disputed Scoring',items:['Sleeper official scoring is final.','The Commissioner may correct platform errors within 24 hours after a weekly period closes.']},
{type:'list',title:'12.3 NFL Work Stoppages',items:['The Commissioner convenes a league vote to determine the response.','No fees are forfeited due to an externally caused suspension.']},
{type:'list',title:'12.4 Taxi Promotion Deadline',items:['Owners must promote or release ineligible taxi players before the regular season in Year 3.','Failure results in automatic release.']},
{type:'list',title:'12.5 Playoff Trade Restrictions',items:['A team is considered a playoff team when the bracket locks.','Eliminated teams return to unrestricted trading immediately after elimination.']}]},
{id:'section-13',number:'13',tab:'governance',title:'Amendments & Charter Updates',intro:'This charter may be amended through a two-thirds supermajority vote.',blocks:[
{type:'list',items:['Any owner may propose an amendment in writing to the Commissioner or through The Combine hub.','At least five days are provided for review before a vote.','The vote window is 72 hours and requires a two-thirds majority.','Standard amendments take effect at the start of the next season.','Emergency amendments require a two-thirds majority and take effect immediately.','The Commissioner may not unilaterally amend the charter.','The charter is reviewed and reaffirmed annually before each season.']},
{type:'note',text:'Every flagged vote item is subject to a Season 1 vote before the startup draft. Results will be recorded on The Combine hub.'}]},
{id:'appendix-a',number:'A',tab:'appendices',title:'Appendix A: Items Pending League Vote',intro:'All items below require a vote before or at the startup draft. Rules take effect as written when no vote occurs.',blocks:[
{type:'table',headers:['#','Item','Options','Default'],rows:[['1','Secondary communication','Sleeper, GroupMe, email, or other','Sleeper chat'],['2','Annual entry fee','$55, $80, or $105 total','CAD $55'],['3','Prize pool split','50/25/15/10 or 60/20/10/10','50/25/15/10'],['4','Taxi squad size','3, 5, or 10','5'],['5','IR spots','3, 5, or 10','5'],['6','Scoring plus TEP','PPR plus 0.25, 0.5, or 1.0 TEP','PPR plus 0.5 TEP'],['7','Rookie draft rounds','3, 4, or 5','3'],['8','FAAB budget','CAD $100 or $200','CAD $100'],['9','Trade deadline','No deadline or standard','No deadline'],['10','Trade veto','No veto, Commissioner only, or 48-hour vote','No veto'],['11','Playoff field','4, 6, or 8','6'],['12','Lineup penalty scale','Confirm or propose an alternative','As chartered']]}]},
{id:'appendix-b',number:'B',tab:'appendices',title:'Appendix B: Quick Reference',blocks:[
{type:'table',headers:['Category','Key Details'],rows:[['Teams','14'],['Annual Fee','CAD $55, $80, or $105. Two years upfront.'],['Payment','E-Transfer to rkunka31@gmail.com'],['Starters','QB, 2 RB, 3 WR, TE, 2 FLEX, 9 total'],['Taxi Squad','5 by default. Year 1 and Year 2 only.'],['IR','5 by default'],['Scoring','Full PPR plus 0.5 TEP by default'],['Startup Draft','Snake, random lottery, 24-hour clock, maximum three extensions'],['Rookie Draft','3 rounds by default, linear order, MaxPF seeding'],['FAAB','CAD $100 by default, resets at training camp and offseason'],['Trades','Auto-approve, no veto by default, playoff restriction'],['Lineup Penalty 1','Formal warning'],['Lineup Penalties 2 through 4','$10, $20, and $40 FAAB fines'],['Lineup Penalty 5 and later','Remaining FAAB plus loss of lowest rookie pick'],['Prize, Champion','50% or 60% of base pool'],['Prize, Runner-Up','25% or 20%'],['Prize, Third Place','15% or 10%'],['Prize, Regular Season','10% for best record'],['Amendments','Two-thirds supermajority'],['Commissioner','Rob Kunka, rkunka31@gmail.com, the-combine.ca']]}]},
{id:'appendix-c',number:'C',tab:'appendices',title:'Appendix C: Owner Contact Directory',intro:'The Commissioner maintains the owner directory. Every owner is responsible for reporting contact changes. The live Contacts section on The Combine hub serves as the current directory.',blocks:[{type:'link',text:'Open the live owner contact directory',view:'contacts'}]}
]};