window.COMBINE_CHARTER={version:'1.1',effective:'2026',title:'The Combine Dynasty Football League Charter',subtitle:'Governing Rules, Bylaws & Operating Procedures',meta:[['Commissioner','Rob Kunka'],['Platform','Sleeper'],['Format','14-team dynasty league'],['Scoring','Official Sleeper league settings'],['Annual Fee','CAD $50 per season'],['Initial Payment','CAD $100 covering Seasons 1 and 2'],['Primary Chat','Sleeper'],['Secondary Chat','WhatsApp'],['Hub','the-combine.ca']],tabs:[['overview','Overview'],['money','Fees & Prizes'],['rosters','Rosters & Scoring'],['drafts','Drafts'],['transactions','Waivers & Trades'],['governance','Governance'],['competition','Season & Playoffs'],['appendices','Appendices'],['bookmarks','Bookmarks']],sections:[
{id:'section-1',number:'1',tab:'overview',title:'League Overview',intro:'This charter governs all rules, conduct, financial obligations, and operating procedures for The Combine Dynasty Football League. Every owner is bound by this charter upon joining. Rosters carry over from season to season and the league operates continuously throughout the year.',blocks:[
{type:'table',title:'1.1 League Structure',headers:['Category','Rule'],rows:[['Teams','14'],['Platform','Sleeper'],['Format','Dynasty, perpetual rosters with no annual re-draft'],['Scoring','Official Sleeper league settings'],['League Type','Competitive, with long-term continuity expected'],['Commissioner','Rob Kunka'],['Hub','the-combine.ca']]},
{type:'text',title:'1.2 Mission Statement',text:'The Combine is designed for committed long-term owners. The league rewards patient roster building, draft strategy, trading, and active team management across multiple seasons. Owners are expected to remain engaged during both the NFL season and the offseason.'},
{type:'text',title:'1.3 Communication',text:'Sleeper league chat is the primary communication channel. WhatsApp is the secondary communication channel. Official announcements and Commissioner decisions may also be posted on The Combine hub. Every owner must keep their email address and phone number current in the league contact directory.'},
{type:'text',title:'1.4 Rule Precedence',text:'Sleeper controls automated scoring, player designations, position eligibility, transaction processing, and other platform mechanics. This charter controls league governance, financial obligations, conduct, penalties, and dispute resolution. When a platform setting conflicts with the charter, the Commissioner will correct the setting or issue a ruling consistent with the charter.'}]},
{id:'section-2',number:'2',tab:'money',title:'League Fees & Payments',intro:'All fees are stated in Canadian dollars. The annual league fee is CAD $50 per team. There is no operational fee.',blocks:[
{type:'table',title:'2.1 Fee Structure',headers:['Item','Amount','Timing'],rows:[['Annual league fee','CAD $50','Each league season'],['Initial payment','CAD $100','Before league activity, covering Seasons 1 and 2'],['Ongoing renewal','CAD $50','Paid before the next unpaid season']]},
{type:'list',title:'2.2 Payment Policy',items:['Two seasons of fees, totaling CAD $100, are due before the startup draft or other league activity.','A team must remain paid through every season in which it owns or has traded away a future rookie pick.','A team with overdue fees is frozen. It may not complete roster moves, trades, waiver claims, or draft selections until payment is received.','After 30 days of non-payment, the Commissioner may begin the replacement process and the owner may forfeit the roster.','Paid fees are not refunded when an owner leaves, is removed, or violates league rules.']},
{type:'text',title:'2.3 Future Pick Payment Obligation',text:'When an owner trades a rookie pick from a future season that has not yet been paid, the CAD $50 fee for that season must be paid within 24 hours of trade acceptance. The trade remains conditional during that period. If payment is not received within 24 hours, the Commissioner will reverse the trade. Payment obligations apply to every future season involved in the transaction.'},
{type:'table',title:'2.4 Prize Distribution',headers:['Prize','Share of Prize Pool'],rows:[['League Champion','60%'],['Runner-Up','20%'],['Third Place','10%'],['Regular Season Winner','10%']]},
{type:'note',text:'The regular-season winner is the owner with the best win-loss record across the regular season. Ties are broken by total Points For.'},
{type:'list',title:'2.5 Ownership Transfers',items:['An owner wishing to transfer or sell a team must notify the Commissioner.','The incoming owner assumes all outstanding financial obligations attached to the team and its future draft picks.','Commissioner approval is required before a transfer is recognized.','Mid-season transfers are permitted only in exceptional circumstances approved by the Commissioner.','Fees already paid are not refunded because of a voluntary departure or rule violation.']},
{type:'text',title:'2.6 League Closure Refunds',text:'If the league folds because of insufficient engagement, inability to maintain a viable number of owners, or another league-wide reason, fees paid for seasons that have not begun will be refunded on a pro-rata basis after league obligations are settled. Fees for a season already underway are not refundable unless the league approves a different resolution.'}]},
{id:'section-3',number:'3',tab:'rosters',title:'Roster Construction',blocks:[
{type:'table',title:'3.1 Active Lineup, Weekly Starters',headers:['Position','Slots','Notes'],rows:[['Quarterback','1',''],['Running Back','2',''],['Wide Receiver','3',''],['Flex, RB/WR/TE','2','Any combination'],['Total Starters','8','No dedicated tight end slot']]},
{type:'table',title:'3.2 Full Roster Composition',headers:['Category','Spots','Eligibility'],rows:[['Starters','8','See Section 3.1'],['Bench','14','All roster-eligible players'],['Taxi Squad','5','Rookies and second-year players only'],['Injured Reserve','5','Players with an official IR designation only']]},
{type:'list',title:'3.3 Taxi Squad Rules',items:['Taxi squad players may be added only during the offseason.','Eligible players are rookies in Year 1 and second-year players in Year 2.','After completing a second NFL season, a player must be promoted or released before Year 3.','Once activated to the active roster, a player cannot return to the taxi squad during that season.','A taxi player may be traded and may remain on the receiving team taxi squad when eligibility and space permit.','Taxi players may not start in weekly lineups.','Taxi spots do not count against the active roster limit.']},
{type:'list',title:'3.4 Injured Reserve',items:['Only players carrying an official IR designation in Sleeper are eligible for an IR slot.','An Out designation by itself does not create IR eligibility under this charter.','Sleeper may block roster moves while an ineligible player occupies an IR slot.','When a player loses IR eligibility, the owner must activate or release the player before completing further transactions.']}]},
{id:'section-4',number:'4',tab:'rosters',title:'Scoring System',intro:'All scoring is governed by the official settings displayed in the Sleeper league. The Sleeper settings page is the authoritative scoring reference.',blocks:[
{type:'text',title:'4.1 Official Settings',text:'Owners are responsible for reviewing the current Sleeper scoring settings. The Commissioner will not maintain a duplicate scoring table in the charter. A scoring-setting change requires the amendment process in Section 13 and will not take effect mid-season unless required to correct an obvious platform configuration error.'},
{type:'text',title:'4.2 Stat Corrections',text:'Sleeper official stat corrections are final. Matchup results update automatically when Sleeper applies a correction.'}]},
{id:'section-5',number:'5',tab:'drafts',title:'Startup Draft',intro:'The startup draft is a one-time snake draft containing all eligible NFL players, including current-year rookies.',blocks:[
{type:'list',items:['Draft order is determined by random lottery.','The order reverses each round.','Drafted players and future rookie picks may be traded during the startup draft.','The pick clock is 24 hours. An expired clock triggers owner notification and one automatic 12-hour extension. Auto-draft activates when the extension expires.','Each owner receives a maximum of three extensions during the startup draft.','Extensions are non-transferable and do not carry over to later drafts.','Owners should maintain a Sleeper draft queue when they expect to be unavailable.']},
{type:'note',text:'The Commissioner will make reasonable efforts to accommodate scheduling issues, but the clock will be enforced consistently.'}]},
{id:'section-6',number:'6',tab:'drafts',title:'Annual Rookie Draft',intro:'The annual rookie draft consists of three linear rounds. Only players entering their first NFL season are eligible. Undrafted rookies enter the waiver or free-agent pool after the draft.',blocks:[
{type:'table',title:'6.1 Draft Format',headers:['Rule','Setting'],rows:[['Rounds','3'],['Format','Linear, not snake'],['Non-playoff order','Lowest to highest regular-season MaxPF'],['Playoff order','Inverse playoff finish'],['Champion','Last pick in each round']]},
{type:'list',title:'6.2 Draft Order',items:['Non-playoff teams are ordered by regular-season Maximum Points For from lowest to highest.','MaxPF ties are broken by head-to-head record, then a Commissioner-supervised random draw.','First-round playoff exits select before semifinal losers.','The championship runner-up selects second-last among playoff teams.','The champion selects last.','The same order applies in all three rounds.']},
{type:'list',title:'6.3 Pick Trading',items:['Future rookie picks may be traded without a limit on years out.','All trades are unconditional. Contingent side agreements are prohibited.','A trade involving an unpaid future season is subject to the 24-hour payment rule in Section 2.3.','Failure to pay within 24 hours results in reversal of the entire trade.']}]},
{id:'section-7',number:'7',tab:'transactions',title:'Waivers & Free Agency',blocks:[
{type:'table',title:'7.1 FAAB System',headers:['Rule','Setting'],rows:[['Budget','$100 per team per FAAB period'],['Bidding','Blind simultaneous bids'],['Winning bid','Highest valid bid'],['Tie-breaker','Sleeper waiver priority'],['Minimum bid','$0'],['Pickup limits','No weekly or seasonal limit, subject to roster space'],['Resets','According to the Commissioner-set Sleeper schedule']]},
{type:'list',title:'7.2 Waiver Processing',items:['Waivers process on the schedule configured in Sleeper.','Dropped players return to waivers before becoming free agents.','Owners are responsible for maintaining legal roster and IR configurations before submitting claims.']}]},
{id:'section-8',number:'8',tab:'transactions',title:'Trade Rules',blocks:[
{type:'list',title:'8.1 Trade Approval',items:['Trades auto-process when accepted by all parties, subject to future-pick payment obligations.','A trade will not be reversed because it appears uneven, unpopular, or risky.','A trade may be reversed only for obvious collusion.','The Commissioner makes the initial collusion determination and presents the matter to a league vote.','A majority of non-involved owners must support reversal before the Commissioner voids the trade.','The Commissioner and every owner directly involved in the trade must abstain from the reversal vote.']},
{type:'text',title:'8.2 Trade Deadline',text:'The standard trade deadline is Week 14. No trades may be completed after the Week 14 deadline until offseason trading reopens after the league championship.'},
{type:'list',title:'8.3 Collusion Review',items:['Collusion involves coordinated conduct intended to improperly benefit one team or harm league competition.','Reports must be submitted to the Commissioner with relevant context.','The Commissioner may review trade history, communications supplied by the parties, payment status, and related transactions.','Obvious collusion may result in trade reversal, loss of FAAB or picks, suspension, or removal.','Repeat collusion results in removal without a refund.']}]},
{id:'section-9',number:'9',tab:'governance',title:'Lineup Management & Penalties',blocks:[
{type:'list',title:'9.1 Lineup Submission',items:['Every owner must submit a complete and legal lineup each week.','Individual lineup slots lock at the applicable player game time.','Owners are responsible for replacing players who are on bye, inactive, injured, or otherwise unavailable.','A good-faith lineup means starting active players with a reasonable expectation of playing. Deliberately weakening a lineup to alter standings or draft order is prohibited.']},
{type:'table',title:'9.2 Penalty Schedule',headers:['Offense','Penalty'],rows:[['First','Formal documented warning'],['Second','$25 FAAB deduction'],['Third and each later offense','All remaining FAAB is removed']]},
{type:'list',title:'9.3 Escalation When No FAAB Remains',items:['When a third or later offense occurs and the owner has no FAAB remaining, the owner loses the lowest-seeded rookie pick they own in the next season.','If the owner has no eligible pick in the next season, the lowest-seeded rookie pick from the next paid season is removed.','If no eligible paid-season pick remains, the owner league standing and continued membership are reviewed by the Commissioner and the league.','The offense counter resets after each completed league season.','An appeal must be submitted within 48 hours with supporting evidence.']},
{type:'note',text:'A documented Sleeper outage or other platform-wide failure affecting multiple owners will not result in a lineup penalty.'}]},
{id:'section-10',number:'10',tab:'governance',title:'Conduct & Governance',blocks:[
{type:'list',title:'10.1 Expected Conduct',items:['Compete in good faith every week.','Remain responsive to league communications and trade offers.','Participate in league drafts or provide advance notice of an absence.','Maintain a respectful tone in Sleeper, WhatsApp, and all league communications.','Notify the Commissioner promptly when unable to continue as an owner.','Do not coordinate lineups, trades, waivers, or payments to manipulate league outcomes.']},
{type:'list',title:'10.2 Orphaned Teams',items:['The Commissioner will make reasonable efforts to contact an unresponsive owner before declaring a team orphaned.','An orphaned team operates in maintenance-only mode, with legal lineups set using reasonable projections and no discretionary trades.','The Commissioner will seek a replacement owner as soon as practical.','The departing owner has no claim to paid fees or prize money unless the league itself folds under Section 2.6.']},
{type:'text',title:'10.3 Team Dissolution & League Viability',text:'The Combine should maintain an even number of teams. The preferred response to a vacancy is replacement of the owner with the roster and draft capital intact. Dissolution or contraction requires league approval and a Commissioner plan covering players, picks, schedules, and unused future-season fees.'},
{type:'list',title:'10.4 Commissioner Authority',items:['Interpret and enforce this charter.','Issue warnings and apply FAAB or draft-pick penalties.','Freeze teams for unpaid fees or illegal rosters.','Investigate suspected collusion or misconduct.','Call league votes and maintain an official record of decisions.','Suspend or remove an owner for serious or repeated violations.']},
{type:'list',title:'10.5 Limits on Commissioner Authority',items:['The Commissioner may not alter rosters for competitive advantage.','The Commissioner may not reverse an uneven trade without the collusion process in Section 8.','The Commissioner may not change scoring settings mid-season except to correct an obvious configuration error.','The Commissioner may not amend the charter unilaterally.']},
{type:'text',title:'10.6 Appeals',text:'An owner may appeal a Commissioner ruling through the league hub, Sleeper, or WhatsApp. A majority of all non-conflicted owners may overturn the ruling. The Commissioner does not vote on an appeal of their own decision.'},
{type:'text',title:'10.7 League Votes',text:'Routine league decisions require a simple majority of votes cast. Charter amendments, owner removal, league contraction, and league dissolution require approval from two-thirds of all active owners. A standard voting window is 72 hours unless an emergency requires a shorter period.'},
{type:'text',title:'10.8 Commissioner Succession',text:'When the Commissioner steps down, the league elects a replacement. Thirty days notice is preferred. If departure is immediate, the longest-tenured available owner serves as interim Commissioner until an election is completed.'}]},
{id:'section-11',number:'11',tab:'competition',title:'Regular Season & Playoffs',blocks:[
{type:'list',title:'11.1 Regular Season',items:['The regular season follows the schedule configured in Sleeper.','Head-to-head matchups and standings are administered by Sleeper.','Win-loss record is the primary standings measure. Sleeper league settings govern published tiebreakers.']},
{type:'text',title:'11.2 Playoffs',text:'The playoff field, seeding, bracket, and matchup weeks follow the official Sleeper league settings. Changes require the charter amendment process and take effect no earlier than the following season.'},
{type:'text',title:'11.3 Regular Season Winner',text:'The owner with the best regular-season record receives 10% of the prize pool. Ties are broken by total regular-season Points For.'},
{type:'text',title:'11.4 Consolation Bracket',text:'Consolation results do not determine rookie draft order. Non-playoff rookie draft order is based on regular-season MaxPF.'}]},
{id:'section-12',number:'12',tab:'competition',title:'Scenarios & Edge Cases',blocks:[
{type:'list',title:'12.1 Player Eligibility',items:['Sleeper position and player-status designations apply immediately.','No retroactive lineup changes are made because of a later eligibility update.']},
{type:'list',title:'12.2 Disputed Scoring',items:['Sleeper official scoring and stat corrections are final.','The Commissioner may correct a clear league-setting or platform-entry error when supported by Sleeper records.']},
{type:'text',title:'12.3 NFL Work Stoppages or Cancelled Games',text:'The Commissioner will propose a fair resolution based on Sleeper treatment, affected matchups, and the scope of the disruption. A league-wide resolution requires a majority vote unless Sleeper applies a uniform final result.'},
{type:'text',title:'12.4 Taxi Promotion Deadline',text:'An ineligible taxi player must be promoted or released before the regular season begins. Failure to resolve the roster may result in automatic release or a frozen roster.'},
{type:'text',title:'12.5 Unaddressed Circumstances',text:'When this charter does not address a situation, the Commissioner will issue a temporary ruling guided by competitive fairness, consistency, prior league decisions, and the long-term health of the league. A permanent rule change follows Section 13.'}]},
{id:'section-13',number:'13',tab:'governance',title:'Amendments & Charter Updates',intro:'This charter is intended to remain stable while allowing the league to address new circumstances.',blocks:[
{type:'list',items:['Any owner may submit a written amendment proposal.','Owners receive at least five days to review a standard proposal before voting.','The voting window is 72 hours.','A charter amendment requires approval from two-thirds of all active owners.','Standard amendments take effect at the start of the next season.','An emergency amendment may take effect immediately when approved by two-thirds of all active owners.','The Commissioner may not amend the charter unilaterally.','The charter is reviewed before each season.']}]},
{id:'appendix-a',number:'A',tab:'appendices',title:'Finalized League Settings',blocks:[
{type:'table',headers:['Category','Adopted Rule'],rows:[['Secondary communication','WhatsApp'],['Annual fee','CAD $50'],['Initial payment','CAD $100 covering Seasons 1 and 2'],['Prize distribution','60% / 20% / 10% / 10%'],['Starting lineup','1 QB, 2 RB, 3 WR, 2 FLEX'],['Bench','14'],['Taxi squad','5, offseason additions only'],['IR','5, official IR designation only'],['Scoring','Official Sleeper settings'],['Rookie draft','3 linear rounds'],['FAAB','$100'],['Trade reversal','Obvious collusion only, Commissioner review plus league vote'],['Trade deadline','Week 14'],['Lineup penalties','Warning, then $25 FAAB, then remaining FAAB with pick escalation']] }]},
{id:'appendix-b',number:'B',tab:'appendices',title:'Quick Reference',blocks:[
{type:'table',headers:['Category','Key Details'],rows:[['Teams','14'],['Fee','CAD $50 per season'],['Initial payment','CAD $100 for Seasons 1 and 2'],['Future pick payment','Pay the applicable season within 24 hours or the trade is reversed'],['Starters','1 QB, 2 RB, 3 WR, 2 FLEX'],['Bench','14'],['Taxi','5, rookies and Year 2 players, offseason additions only'],['IR','5, official IR designation only'],['Rookie draft','3 rounds, linear, MaxPF order for non-playoff teams'],['FAAB','$100'],['Trades','Auto-process, Week 14 deadline, collusion reversal only'],['Prizes','60% champion, 20% runner-up, 10% third, 10% regular-season winner'],['Amendments','Two-thirds of all active owners']] }]},
{id:'appendix-c',number:'C',tab:'appendices',title:'Owner Contact Directory',intro:'The live owner directory is maintained on The Combine hub. Every owner must notify the Commissioner when their contact information changes.',blocks:[{type:'link',view:'contacts',text:'Open the live owner contact directory'}]}]};