(()=>{
window.status=function(type,label){const el=document.querySelector('#live-status');if(!el)return;el.className=`live-status ${type||''}`;const text=el.querySelector('span');if(text)text.textContent=label||'';};
const DATA=window.COMBINE_CHARTER;if(!DATA)return;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activeTab='overview',query='',bookmarks=new Set(JSON.parse(localStorage.getItem('combine_charter_bookmarks')||'[]'));
const normalize=s=>String(s||'').toLowerCase();
const sectionText=s=>[s.number,s.title,s.intro,...(s.blocks||[]).flatMap(b=>[b.title,b.text,...(b.items||[]),...(b.headers||[]),...(b.rows||[]).flat()])].join(' ');
function saveBookmarks(){localStorage.setItem('combine_charter_bookmarks',JSON.stringify([...bookmarks]));}
function mark(text){if(!query)return esc(text);const safe=esc(text),q=query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return safe.replace(new RegExp(`(${q})`,'ig'),'<mark>$1</mark>');}
function blockHTML(b){
 if(b.type==='text')return `<div class="charter-block"><h3>${mark(b.title)}</h3><p>${mark(b.text)}</p></div>`;
 if(b.type==='list')return `<div class="charter-block">${b.title?`<h3>${mark(b.title)}</h3>`:''}<ul>${b.items.map(x=>`<li>${mark(x)}</li>`).join('')}</ul></div>`;
 if(b.type==='table')return `<div class="charter-block">${b.title?`<h3>${mark(b.title)}</h3>`:''}<div class="charter-table-wrap"><table class="charter-table"><thead><tr>${b.headers.map(x=>`<th>${mark(x)}</th>`).join('')}</tr></thead><tbody>${b.rows.map(r=>`<tr>${r.map(x=>`<td>${mark(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;
 if(b.type==='vote')return `<div class="charter-callout vote"><strong>League Vote</strong><span>${mark(b.text)}</span></div>`;
 if(b.type==='note')return `<div class="charter-callout note"><strong>Rule Note</strong><span>${mark(b.text)}</span></div>`;
 if(b.type==='link')return `<button class="charter-view-link" data-charter-view="${esc(b.view)}">${esc(b.text)} →</button>`;
 return '';
}
function sectionHTML(s){const saved=bookmarks.has(s.id);return `<section class="charter-section" id="${s.id}" data-tab="${s.tab}"><header class="charter-section-head"><div><span class="charter-number">${esc(s.number)}</span><h2>${mark(s.title)}</h2></div><div class="charter-section-actions"><button class="charter-copy-link" data-copy="${s.id}" title="Copy direct link">Link</button><button class="charter-bookmark${saved?' saved':''}" data-bookmark="${s.id}" aria-label="${saved?'Remove bookmark':'Save bookmark'}">${saved?'★':'☆'}</button></div></header>${s.intro?`<p class="charter-intro">${mark(s.intro)}</p>`:''}${(s.blocks||[]).map(blockHTML).join('')}</section>`;}
function visibleSections(){let list=DATA.sections;if(activeTab==='bookmarks')list=list.filter(s=>bookmarks.has(s.id));else list=list.filter(s=>s.tab===activeTab);if(query)list=list.filter(s=>normalize(sectionText(s)).includes(normalize(query)));return list;}
function renderTabs(){const el=$('#charter-tabs');if(!el)return;el.innerHTML=DATA.tabs.map(([id,label])=>`<button class="charter-tab${activeTab===id?' active':''}" data-charter-tab="${id}">${esc(label)}${id==='bookmarks'&&bookmarks.size?` <span>${bookmarks.size}</span>`:''}</button>`).join('');el.querySelectorAll('[data-charter-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.charterTab;query='';const input=$('#charter-search');if(input)input.value='';render();});}
function renderTOC(list){const el=$('#charter-toc');if(!el)return;el.innerHTML=list.length?list.map(s=>`<a href="#${s.id}" data-charter-section="${s.id}"><span>${esc(s.number)}</span>${esc(s.title)}</a>`).join(''):'<p class="charter-empty-small">No sections in this view.</p>';el.querySelectorAll('[data-charter-section]').forEach(a=>a.onclick=e=>{e.preventDefault();openSection(a.dataset.charterSection,true);});}
function render(){const list=visibleSections();renderTabs();renderTOC(list);const el=$('#charter-sections');if(!el)return;el.innerHTML=list.length?list.map(sectionHTML).join(''):`<div class="charter-empty"><strong>No matching rules</strong><p>Try another search or tab.</p></div>`;bindSectionActions();}
function bindSectionActions(){document.querySelectorAll('[data-bookmark]').forEach(b=>b.onclick=()=>{const id=b.dataset.bookmark;bookmarks.has(id)?bookmarks.delete(id):bookmarks.add(id);saveBookmarks();render();});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const url=`${location.origin}${location.pathname}#charter-${b.dataset.copy}`;try{await navigator.clipboard.writeText(url);if(window.toast)toast('Charter link copied.');}catch{prompt('Copy this charter link:',url);}});document.querySelectorAll('[data-charter-view]').forEach(b=>b.onclick=()=>{if(window.show)show(b.dataset.charterView);});}
function openSection(id,push=false){const s=DATA.sections.find(x=>x.id===id);if(!s)return;activeTab=s.tab;query='';render();requestAnimationFrame(()=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});});if(push)history.replaceState(null,'',`#charter-${id}`);}
function shell(){const copy=$('#charter-copy'),nav=$('#charter-nav');if(!copy||!nav)return;const meta=DATA.meta.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');nav.outerHTML=`<aside class="panel charter-sidebar" id="charter-nav"><div class="charter-search-wrap"><label for="charter-search">Search charter</label><input id="charter-search" class="control" type="search" placeholder="Search rules, fees, trades..."><span id="charter-search-count"></span></div><nav class="charter-toc" id="charter-toc"></nav></aside>`;copy.outerHTML=`<article class="charter-main" id="charter-copy"><section class="panel charter-cover"><p class="kicker">OFFICIAL LEAGUE CHARTER</p><h2>${esc(DATA.title)}</h2><p>${esc(DATA.subtitle)}</p><div class="charter-cover-meta">${meta}</div><div class="charter-version">Version ${esc(DATA.version)} · Effective ${esc(DATA.effective)}</div></section><div class="charter-tabs" id="charter-tabs"></div><div id="charter-sections"></div></article>`;const input=$('#charter-search');input.addEventListener('input',()=>{query=input.value.trim();const matches=DATA.sections.filter(s=>normalize(sectionText(s)).includes(normalize(query))).length;$('#charter-search-count').textContent=query?`${matches} section${matches===1?'':'s'}`:'';render();});render();}
window.charter=function(){shell();};
document.addEventListener('DOMContentLoaded',()=>{const h=location.hash.slice(1);if(h.startsWith('charter-section-')||h.startsWith('charter-appendix-')){if(window.show)show('charter');setTimeout(()=>openSection(h.replace(/^charter-/,'')),0);}});
setTimeout(()=>{if(typeof window.load==='function')window.load();},0);
})();
const combineEnhancements=document.createElement('script');combineEnhancements.src='enhancements.js?v=20260712b';document.head.appendChild(combineEnhancements);