(()=>{
const API='https://api.sleeper.app/v1',LEAGUE='1315912688991227904',WORKER='https://the-combine.rkunka31.workers.dev';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=async p=>{const r=await fetch(API+p,{cache:'no-store'});if(!r.ok)throw Error(p);return r.json()};
let users=[],rosters=[],players={},drafts=[],picks=[],draft=null,um=new Map(),rm=new Map();
const team=r=>{const u=um.get(r?.owner_id);return u?.metadata?.team_name||u?.display_name||`Team ${r?.roster_id||''}`};
const owner=r=>um.get(r?.owner_id)?.display_name||'Vacant';
const who=id=>{const r=rm.get(Number(id));return r?`${team(r)} (${owner(r)})`:'Unknown team'};
function addNav(){const pairs=[['payments','Payments'],['autopsy','Roster Autopsy']];pairs.forEach(([id,label])=>{if(document.querySelector(`[data-view="${id}"]`))return;document.querySelectorAll('#desktop-nav,#mobile-menu').forEach(n=>n?.insertAdjacentHTML('beforeend',`<button class="nav-link" data-view="${id}">${label}</button>`));});document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${b.dataset.view}`));document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===b.dataset.view));$('#mobile-menu')?.classList.remove('open');history.replaceState(null,'',`#${b.dataset.view}`);scrollTo(0,0)});}
function addViews(){const main=document.querySelector('main');if(!main)return;if(!$('#view-payments'))main.insertAdjacentHTML('beforeend',`<section class="view" id="view-payments"><div class="page-head shell"><p class="eyebrow">LEAGUE TREASURY</p><h1>Payment tracker</h1><p>All teams are paid for 2026 and 2027.</p></div><div class="shell"><div id="payment-v2" class="panel"></div></div></section>`);if(!$('#view-autopsy'))main.insertAdjacentHTML('beforeend',`<section class="view" id="view-autopsy"><div class="page-head shell"><p class="eyebrow">THE ROSTER MORGUE</p><h1>Roster Autopsy</h1><p>Every franchise gets a grade and a bruise.</p></div><div class="shell"><div style="margin-bottom:16px"><button class="primary-button" id="autopsy-ai-v2">Run AI roster autopsy</button></div><div id="autopsy-v2" class="loading-block">Loading rosters...</div></div></section>`);}
function css(){if($('#features-v2-css'))return;const s=document.createElement('style');s.id='features-v2-css';s.textContent=`.v2-owner{display:block;color:var(--gold);font-size:11px;margin-bottom:4px}.v2-trade{display:block;margin-top:5px;color:var(--gold);font-size:11px}.v2-round{padding:20px 0;border-bottom:1px solid var(--line)}.v2-round:last-child{border-bottom:0}.v2-pick{margin:10px 0;line-height:1.55}.v2-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.v2-grade{padding:20px;position:relative}.v2-rank{position:absolute;right:18px;top:16px;font:700 30px var(--display);color:var(--gold)}.v2-grade h3{font:600 23px var(--display);text-transform:uppercase;margin-right:55px}.v2-score{font:700 34px var(--display);color:var(--cream);margin:10px 0}.v2-bars{display:grid;gap:7px}.v2-line{display:grid;grid-template-columns:95px 1fr 34px;gap:8px;align-items:center;font-size:10px;color:var(--muted);text-transform:uppercase}.v2-line i{height:6px;background:rgba(255,255,255,.08);border-radius:8px}.v2-line i:after{content:'';display:block;height:100%;width:var(--w);background:var(--gold);border-radius:8px}.v2-paid{display:grid;grid-template-columns:44px 1fr auto auto;gap:12px;align-items:center;padding:15px;border-bottom:1px solid var(--line)}.v2-badge{padding:5px 9px;border-radius:16px;background:rgba(98,211,148,.12);color:#75d8a0;font-size:10px;font-weight:700}@media(max-width:760px){.v2-grid{grid-template-columns:1fr}.v2-paid{grid-template-columns:40px 1fr}.v2-badge{justify-self:start}}`;document.head.appendChild(s)}
function originalOwner(p){const m=draft?.slot_to_roster_id||draft?.settings?.slot_to_roster_id||{};return Number(m[p.draft_slot]||0)||null}
function roastText(round,arr){const trades=arr.filter(x=>x.traded);const counts={};arr.forEach(x=>counts[x.pos]=(counts[x.pos]||0)+1);const run=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];let t=`Round ${round} featured ${arr.length} picks`;if(run)t+=`, including ${run[1]} ${run[0]} selections`;t+='.';if(trades.length)t+=` ${trades.length} draft slot${trades.length===1?' was':'s were'} traded, so the original order lasted about as long as most preseason hype.`;else t+=' Nobody traded a slot, which qualifies as restraint by dynasty standards.';return t}
function renderRoast(){const out=$('#draft-recap-copy');if(!out||!picks.length)return;const info=picks.map(p=>{const orig=originalOwner(p),sel=Number(p.roster_id);return{round:p.round,pick:p.pick_no,player:`${p.metadata?.first_name||''} ${p.metadata?.last_name||''}`.trim(),pos:p.metadata?.position||'',orig,sel,traded:!!(orig&&sel&&orig!==sel)}});const by={};info.forEach(x=>(by[x.round]??=[]).push(x));out.innerHTML=`<h2>Draft recap and roast</h2><p>${info.length} picks reviewed. Traded draft slots are shown with both the original owner and selecting team.</p>${Object.entries(by).map(([r,a])=>`<section class="v2-round"><h2>Round ${r}</h2><p>${esc(roastText(r,a))}</p>${a.map(x=>`<div class="v2-pick"><strong>${x.pick}. ${esc(x.player)}</strong> · ${esc(who(x.sel))}${x.traded?`<span class="v2-trade">Draft slot traded from ${esc(who(x.orig))} to ${esc(who(x.sel))}</span>`:''}</div>`).join('')}</section>`).join('')}`;}
async function aiRoast(){const btn=$('#generate-draft-roast'),out=$('#draft-recap-copy');if(!btn||!out)return;btn.disabled=true;btn.textContent='Writing the roast...';try{const data=picks.map(p=>({pick:p.pick_no,round:p.round,player:`${p.metadata?.first_name||''} ${p.metadata?.last_name||''}`.trim(),position:p.metadata?.position||'',original_owner:who(originalOwner(p)),selecting_team:who(p.roster_id),traded:originalOwner(p)!==Number(p.roster_id)}));const r=await fetch(`${WORKER}/ai`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-opus-4-5',max_tokens:3000,system:'Write a detailed dynasty startup draft roast in clean HTML. Cover every round, cite specific reaches and values, and explain traded draft slots. Be funny and critical without personal attacks.',messages:[{role:'user',content:JSON.stringify(data)}]})});if(!r.ok)throw Error();const d=await r.json();out.innerHTML=d.content?.[0]?.text||'';if(!out.textContent.trim())throw Error()}catch{renderRoast()}finally{btn.disabled=false;btn.textContent='Regenerate detailed roast'}}
function payments(){const el=$('#payment-v2');if(!el)return;el.innerHTML=rosters.map(r=>`<div class="v2-paid"><span class="avatar">${esc(team(r).slice(0,2).toUpperCase())}</span><div><strong>${esc(team(r))}</strong><small>${esc(owner(r))}</small></div><span class="v2-badge">2026 PAID</span><span class="v2-badge">2027 PAID</span></div>`).join('')}
function grades(){return rosters.map(r=>{const ps=(r.players||[]).map(id=>players[id]).filter(Boolean),ages=ps.map(p=>+p.age).filter(Boolean),age=ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:27,c={};['QB','RB','WR','TE'].forEach(x=>c[x]=ps.filter(p=>p.position===x).length);const dynasty=Math.max(45,Math.min(95,Math.round(94-(age-24)*5))),balance=Math.max(45,100-(Math.abs(c.QB-3)*5+Math.abs(c.RB-6)*4+Math.abs(c.WR-8)*3+Math.abs(c.TE-3)*5)),depth=Math.min(95,50+ps.length*1.6),redraft=Math.max(45,Math.min(95,Math.round(60+(r.settings?.fpts||0)/100))),capital=70,overall=Math.round(dynasty*.3+redraft*.25+balance*.2+depth*.15+capital*.1);return{r,team:team(r),owner:owner(r),dynasty,redraft,balance:Math.round(balance),depth:Math.round(depth),capital,overall,summary:`${dynasty>=redraft?'The long-term outlook is stronger than the immediate lineup.':'The current lineup is doing more work than the future profile.'} Positional balance scores ${Math.round(balance)}, so at least the roster construction has a pulse.`}}).sort((a,b)=>b.overall-a.overall)}
function renderGrades(){const el=$('#autopsy-v2');if(!el)return;const g=grades();el.innerHTML=`<div class="v2-grid">${g.map((x,i)=>`<article class="panel v2-grade"><span class="v2-rank">#${i+1}</span><h3>${esc(x.team)}</h3><p>${esc(x.owner)}</p><div class="v2-bars">${[['Dynasty',x.dynasty],['Redraft',x.redraft],['Balance',x.balance],['Depth',x.depth],['Draft capital',x.capital]].map(([l,v])=>`<div class="v2-line"><span>${l}</span><i style="--w:${v}%"></i><b>${v}</b></div>`).join('')}</div><div class="v2-score">${x.overall}/100</div><p>${esc(x.summary)}</p></article>`).join('')}</div>`}
async function init(){css();addViews();addNav();try{[users,rosters,players,drafts]=await Promise.all([get(`/league/${LEAGUE}/users`),get(`/league/${LEAGUE}/rosters`),get('/players/nfl'),get(`/league/${LEAGUE}/drafts`)]);users.forEach(u=>um.set(u.user_id,u));rosters.forEach(r=>rm.set(r.roster_id,r));draft=drafts.find(d=>d.status==='complete')||drafts[0];if(draft)picks=await get(`/draft/${draft.draft_id}/picks`);payments();renderGrades();renderRoast();const btn=$('#generate-draft-roast');if(btn)btn.onclick=aiRoast;const ab=$('#autopsy-ai-v2');if(ab)ab.onclick=()=>{renderGrades();ab.textContent='Autopsy refreshed';setTimeout(()=>ab.textContent='Run AI roster autopsy',1500)}}catch(e){console.error('features-v2',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();