(()=>{
const API='https://api.sleeper.app/v1',LEAGUE='1315912688991227904';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(p){const r=await fetch(API+p,{cache:'no-store'});if(!r.ok)throw Error(p);return r.json()}
function stripDuplicateViews(){['activity','teams','team','rules'].forEach(v=>{const view=$(`#view-${v}`);if(view)view.remove();$$(`[data-view="${v}"]`).forEach(x=>x.remove())});const pulse=$('.pulse-panel');if(pulse)pulse.remove();const grid=$('.dashboard-grid'),brief=$('.briefing-panel');if(grid&&brief)grid.prepend(brief);if(brief){const k=brief.querySelector('.kicker');if(k)k.textContent="COMMISSIONER'S DESK";const h=brief.querySelector('h2');if(h)h.textContent='Weekly league commentary';const b=brief.querySelector('[data-jump]');if(b){b.dataset.jump='report';b.textContent='Full commentary →'}}}
function nameMaps(users,rosters){const um=new Map(users.map(u=>[u.user_id,u])),rm=new Map(rosters.map(r=>[r.roster_id,r]));const team=r=>{const u=um.get(r?.owner_id);return u?.metadata?.team_name||u?.display_name||`Team ${r?.roster_id||''}`};const owner=r=>um.get(r?.owner_id)?.display_name||'Vacant';return{um,rm,team,owner}}
async function weeklyDesk(users,rosters,state,maps){const week=Math.max(1,(state.week||1)-1),box=$('#briefing-copy'),report=$('#report-copy');if(!box||!report)return;let matchups=[],tx=[];try{[matchups,tx]=await Promise.all([get(`/league/${LEAGUE}/matchups/${week}`),get(`/league/${LEAGUE}/transactions/${week}`)])}catch{}
const pairs=new Map();matchups.forEach(m=>{const a=pairs.get(m.matchup_id)||[];a.push(m);pairs.set(m.matchup_id,a)});const finals=[...pairs.values()].filter(x=>x.length===2).map(([a,b])=>({a,b,w:a.points>=b.points?a:b,l:a.points>=b.points?b:a,margin:Math.abs((a.points||0)-(b.points||0))}));const biggest=finals.sort((a,b)=>b.margin-a.margin)[0];const top=[...matchups].sort((a,b)=>(b.points||0)-(a.points||0))[0];const movers=tx.filter(t=>t.type==='trade').length;let short='The league is in preseason mode. Weekly results and player trends will populate once games begin.';let full='<h2>State of the league</h2><p>The dashboard is ready for weekly scoring, lineup results and transaction context once the season starts.</p>';
if(matchups.length){const rTop=maps.rm.get(top?.roster_id),rW=maps.rm.get(biggest?.w?.roster_id),rL=maps.rm.get(biggest?.l?.roster_id);short=`${maps.team(rTop)} led Week ${week} with ${(top.points||0).toFixed(1)} points. ${maps.team(rW)} posted the largest win, beating ${maps.team(rL)} by ${(biggest.margin||0).toFixed(1)}. ${movers} trade${movers===1?'':'s'} hit the wire.`;full=`<h2>Week ${week} recap</h2><p>${esc(maps.team(rTop))} set the weekly pace with ${(top.points||0).toFixed(1)} points. ${esc(maps.team(rW))} delivered the widest margin, handling ${esc(maps.team(rL))} by ${(biggest.margin||0).toFixed(1)}.</p><h2>League movement</h2><p>${movers} trade${movers===1?'':'s'} were processed during the week. Standings movement and player-level leaders will update as the 2026 schedule produces more data.</p>`}
box.textContent=short;report.innerHTML=full}
function originalRosterForPick(d,p,users,rosters){const order=d.draft_order||{};const userId=Object.keys(order).find(uid=>Number(order[uid])===Number(p.draft_slot));return userId?rosters.find(r=>r.owner_id===userId):null}
function roundComment(round,picks,maps){const pos={};picks.forEach(x=>pos[x.position]=(pos[x.position]||0)+1);const run=Object.entries(pos).sort((a,b)=>b[1]-a[1])[0];const traded=picks.filter(x=>x.traded);const first=picks[0],last=picks[picks.length-1];let s=`Round ${round} leaned ${run?`${run[0]}-heavy with ${run[1]} selections`:'into a mixed board'}. `;if(traded.length)s+=`${traded.length} pick${traded.length===1?' changed':'s changed'} hands before the card was turned in. `;if(first)s+=`${first.team} opened with ${first.player}. `;if(last)s+=`${last.team} closed with ${last.player}.`;return s}
async function rebuildDraft(users,rosters,maps){const target=$('#draft-recap-copy');if(!target)return;try{const drafts=await get(`/league/${LEAGUE}/drafts`),d=drafts.find(x=>x.status==='complete')||drafts[0];if(!d)return;const picks=await get(`/draft/${d.draft_id}/picks`);const rows=picks.map(p=>{const selected=maps.rm.get(Number(p.roster_id)),original=originalRosterForPick(d,p,users,rosters);return{round:p.round,pick:p.pick_no,player:`${p.metadata?.first_name||''} ${p.metadata?.last_name||''}`.trim(),position:p.metadata?.position||'',team:maps.team(selected),owner:maps.owner(selected),originalTeam:original?maps.team(original):'',traded:!!(original&&selected&&original.roster_id!==selected.roster_id)}});const by={};rows.forEach(x=>(by[x.round]??=[]).push(x));target.innerHTML=`<h2>Draft analysis</h2><p>${rows.length} selections reviewed. Traded draft slots are shown using the original slot owner and the team that made the pick.</p>${Object.entries(by).map(([r,a])=>`<section class="round-roast"><h2>Round ${r}</h2><p>${esc(roundComment(r,a,maps))}</p>${a.map(x=>`<p><strong>${x.pick}. ${esc(x.player)}</strong> · ${esc(x.team)} (${esc(x.owner)})${x.traded?`<br><span class="draft-trade">Original slot: ${esc(x.originalTeam)}. Pick used by ${esc(x.team)}.</span>`:''}</p>`).join('')}</section>`).join('')}`;const btn=$('#generate-draft-roast');if(btn){btn.textContent='Refresh draft analysis';btn.onclick=()=>rebuildDraft(users,rosters,maps)}}catch(e){target.innerHTML='<p>Draft analysis could not load. Please refresh the page.</p>'}}
async function init(){stripDuplicateViews();try{const [users,rosters,state]=await Promise.all([get(`/league/${LEAGUE}/users`),get(`/league/${LEAGUE}/rosters`),get('/state/nfl')]);const maps=nameMaps(users,rosters);await Promise.all([weeklyDesk(users,rosters,state,maps),rebuildDraft(users,rosters,maps)])}catch(e){console.error(e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,700);
})();